spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yzhangweber/cloudconfig-piggymetricsweber.git
          search-paths:
            - config*
  #profiles:
  #   active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

